import Link from 'next/link';
import Image from 'next/image';
import { site as libSite, footer as libFooter } from '@/lib/site';

export function Footer({ data, brand }) {
  const footer = data && typeof data === 'object' && !Array.isArray(data) ? data : libFooter;
  const site = brand && typeof brand === 'object' && !Array.isArray(brand) ? brand : libSite;
  return (
    <footer
      className="
        font-grotesk
        border-t-[4px]
        border-[#020F40]
        bg-[var(--bg-surface)]
        text-[var(--text-primary)]
        dark:border-[#11DFF5]
        dark:bg-[#020F40]
        dark:text-white
      "
    >
      {/* top accent */}
      <div
        className="
          h-[3px]
          w-full
          bg-[#11DFF5]
          dark:bg-[#11DFF5]
        "
      />

      <div
        className="
          h-px
          w-full
          bg-gradient-to-r
          from-transparent
          via-[#11DFF5]/30
          to-transparent
          opacity-60
        "
      />

      <div
        className="
          mx-auto
          max-w-[1440px]
          px-4
          sm:px-6
          lg:px-8
          pt-10
          sm:pt-12
          lg:pt-14
        "
      >
        {/* brand row — professional, logo NO BORDER, amazing */}
        <div
          className="
            flex
            flex-col
            gap-8
            lg:flex-row
            lg:items-start
            lg:justify-between
          "
        >
          <div
            className="
              flex
              max-w-[520px]
              flex-col
              gap-4
            "
          >
            <Link
              href="/"
              className="
                inline-flex
                self-start
                focus-visible:outline-none
                focus-visible:ring-2
                focus-visible:ring-[#11DFF5]
                focus-visible:ring-offset-2
                focus-visible:ring-offset-[var(--bg-surface)]
                dark:focus-visible:ring-offset-[#020F40]
              "
            >
              <Image
                src="/thesoftwarebase.png"
                alt={site.name}
                width={560}
                height={126}
                className="
                  h-[84px]
                  w-auto
                  object-contain
                  sm:h-[96px]
                  lg:h-[112px]
                  drop-shadow-[0_4px_16px_rgba(17,223,245,0.20)]
                "
              />
            </Link>

            <p
              className="
                max-w-[420px]
                text-[13px]
                font-medium
                leading-relaxed
                text-[var(--text-secondary)]
                dark:text-white/65
              "
            >
              {footer.tagline}
            </p>

            <div
              className="
                inline-flex
                items-center
                gap-2
                border
                border-[#020F40]/10
                bg-[var(--bg-elevated)]
                px-3
                py-1.5
                text-[11px]
                font-black
                tracking-[0.14em]
                uppercase
                text-[#0D65EF]
                dark:border-white/10
                dark:bg-white/[0.06]
                dark:text-[#11DFF5]
              "
            >
              <span
                className="
                  h-2
                  w-2
                  rounded-full
                  bg-[#11DFF5]
                  shadow-[0_0_10px_#11DFF5]
                  animate-pulse
                "
              />
              {footer.status}
            </div>
          </div>

          <div
            className="
              hidden
              lg:flex
              flex-col
              items-end
              text-right
            "
          >
            <div
              className="
                text-[11px]
                font-black
                tracking-[0.2em]
                uppercase
                text-[var(--text-secondary)]
                dark:text-white/40
              "
            >
              Est. {site.year} — {footer.remoteNote}
            </div>

            <div
              className="
                mt-3
                inline-flex
                border-[2px]
                border-[#020F40]
                bg-[#020F40]
                px-3
                py-1
                text-[10px]
                font-black
                tracking-[0.16em]
                uppercase
                text-[#11DFF5]
                dark:border-[#11DFF5]
                dark:bg-[#11DFF5]
                dark:text-[#020F40]
              "
            >
              {footer.shipNote || ''}
            </div>
          </div>
        </div>

        {/* divider */}
        <div
          className="
            mt-10
            h-px
            w-full
            bg-[#020F40]/10
            dark:bg-white/10
          "
        />

        {/* links grid — theme specific, professional */}
        <div
          className="
            mt-8
            grid
            gap-6
            sm:grid-cols-2
            lg:grid-cols-[1.5fr_0.9fr_1.2fr]
          "
        >
          {/* product — from site.js footer.cols[0] */}
          <div
            className="
              border-[4px]
              border-[#020F40]
              bg-white
              p-5
              shadow-[6px_6px_0_0_#020F40]
              dark:border-white/10
              dark:bg-white/[0.04]
              dark:shadow-none
              sm:p-6
            "
          >
            <div
              className="
                text-[11px]
                font-black
                tracking-[0.18em]
                uppercase
                text-[#0D65EF]
                dark:text-[#11DFF5]
              "
            >
              {footer.cols[0].title}
            </div>

            <ul
              className="
                mt-4
                flex
                flex-col
                gap-2.5
              "
            >
              {footer.cols[0].links.map((l) => (
                <li
                  key={l.href}
                >
                  <Link
                    href={l.href}
                    className="
                      group
                      inline-flex
                      items-center
                      gap-2
                      text-[13px]
                      font-semibold
                      tracking-[0.12em]
                      uppercase
                      text-[var(--text-primary)]
                      transition-colors
                      hover:text-[#0D65EF]
                      dark:text-white/80
                      dark:hover:text-white
                    "
                  >
                    <span
                      className="
                        h-1
                        w-1
                        bg-[#0D65EF]
                        opacity-0
                        transition-opacity
                        group-hover:opacity-100
                        dark:bg-[#11DFF5]
                      "
                    />

                    {l.label}
                  </Link>
                </li>
              ))}
            </ul>

            <div
              className="
                mt-6
                border-t
                border-[#020F40]/10
                pt-4
                dark:border-white/10
              "
            >
              <Link
                href={site.cta.href}
                className="
                  inline-flex
                  w-full
                  items-center
                  justify-center
                  gap-2
                  border-[3px]
                  border-[#020F40]
                  bg-[#0D65EF]
                  px-4
                  py-2.5
                  text-[11px]
                  font-black
                  tracking-[0.14em]
                  uppercase
                  text-white
                  shadow-[3px_3px_0_0_#020F40]
                  transition-all
                  hover:translate-x-px
                  hover:translate-y-px
                  hover:shadow-[2px_2px_0_0_#020F40]
                  dark:border-[#11DFF5]
                  dark:bg-[#11DFF5]
                  dark:text-[#020F40]
                  dark:shadow-[3px_3px_0_0_#11DFF5]
                "
              >
                {site.cta.label}
              </Link>
            </div>
          </div>

          {/* company — from site.js footer.cols[1] */}
          <div
            className="
              border-[4px]
              border-[#020F40]
              bg-white
              p-5
              shadow-[6px_6px_0_0_#020F40]
              dark:border-white/10
              dark:bg-white/[0.04]
              dark:shadow-none
              sm:p-6
            "
          >
            <div
              className="
                text-[11px]
                font-black
                tracking-[0.18em]
                uppercase
                text-[#0D65EF]
                dark:text-[#11DFF5]
              "
            >
              {footer.cols[1].title}
            </div>

            <ul
              className="
                mt-4
                flex
                flex-col
                gap-2.5
              "
            >
              {footer.cols[1].links.map((l) => (
                <li
                  key={l.href}
                >
                  <Link
                    href={l.href}
                    className="
                      group
                      inline-flex
                      items-center
                      gap-2
                      text-[13px]
                      font-semibold
                      tracking-[0.12em]
                      uppercase
                      text-[var(--text-primary)]
                      transition-colors
                      hover:text-[#0D65EF]
                      dark:text-white/80
                      dark:hover:text-white
                    "
                  >
                    <span
                      className="
                        h-1
                        w-1
                        bg-[#0D65EF]
                        opacity-0
                        transition-opacity
                        group-hover:opacity-100
                        dark:bg-[#11DFF5]
                      "
                    />

                    {l.label}
                  </Link>
                </li>
              ))}
            </ul>

            <div
              className="
                mt-6
                rounded-[6px]
                border
                border-[#0D65EF]/15
                bg-[#0D65EF]/5
                px-3
                py-2
                text-[11px]
                font-bold
                tracking-[0.12em]
                uppercase
                text-[#0D65EF]
                dark:border-[#11DFF5]/20
                dark:bg-[#11DFF5]/10
                dark:text-[#C6EAF4]
              "
            >
              {site.year} — {footer.builtNote}
            </div>
          </div>

          {/* manifesto — from site.js footer.manifesto */}
          <div
            className="
              border-[3px]
              border-[#020F40]
              bg-[#020F40]
              p-5
              text-white
              dark:border-[#11DFF5]
              dark:bg-[#11DFF5]
              dark:text-[#020F40]
              sm:p-6
            "
          >
            <div
              className="
                text-[11px]
                font-black
                tracking-[0.18em]
                uppercase
                opacity-60
                dark:opacity-60
              "
            >
              {footer.manifesto.kicker}
            </div>

            <p
              className="
                mt-3
                text-[13px]
                font-bold
                leading-relaxed
                tracking-[-0.01em]
              "
            >
              {footer.manifesto.desc}
            </p>

            <div
              className="
                mt-4
                inline-flex
                border-[2px]
                border-white
                bg-white
                px-3
                py-1
                text-[10px]
                font-black
                tracking-[0.16em]
                uppercase
                text-[#020F40]
                dark:border-[#020F40]
                dark:bg-[#020F40]
                dark:text-[#11DFF5]
              "
            >
              {footer.manifesto.badge}
            </div>
          </div>
        </div>

        {/* bottom — theme specific, professional */}
        <div
          className="
            mt-10
            flex
            flex-col
            gap-4
            border-t
            border-[#020F40]/10
            pt-6
            dark:border-white/10
            sm:flex-row
            sm:items-center
            sm:justify-between
          "
        >
          <div
            className="
              flex
              flex-col
              gap-1
            "
          >
            <p
              className="
                text-[11px]
                font-black
                tracking-[0.14em]
                uppercase
                text-[var(--text-secondary)]
                dark:text-white/60
              "
            >
              {footer.legal}
            </p>

            <p
              className="
                text-[11px]
                font-bold
                tracking-[0.12em]
                uppercase
                text-[var(--text-secondary)]/60
                dark:text-white/30
              "
            >
              {footer.craftedPrefix} {site.year} • {site.shortName}
            </p>
          </div>

          <div
            className="
              flex
              items-center
              gap-3
            "
          >
            <span
              className="
                hidden
                text-[11px]
                font-black
                tracking-[0.14em]
                uppercase
                text-[var(--text-secondary)]/60
                dark:text-white/40
                sm:inline
              "
            >
              {footer.backToTop}
            </span>

            <a
              href="#"
              suppressHydrationWarning
              onClick={(e) => {
                e.preventDefault();
                window.scrollTo({ top: 0, behavior: 'smooth' });
              }}
              className="
                inline-flex
                h-9
                w-9
                items-center
                justify-center
                border-[3px]
                border-[#020F40]
                bg-[var(--bg-surface)]
                text-[#020F40]
                transition-colors
                hover:bg-[#020F40]
                hover:text-white
                dark:border-white
                dark:bg-white
                dark:text-[#020F40]
                dark:hover:bg-[#11DFF5]
                dark:hover:border-[#11DFF5]
              "
            >
              ↑
            </a>
          </div>
        </div>

        {/* watermark — theme specific */}
        <div
          className="
            pointer-events-none
            mt-8
            select-none
            overflow-hidden
            border-t
            border-[#020F40]/5
            pt-6
            dark:border-white/5
          "
        >
          <div
            className="
              text-center
              text-[14vw]
              font-black
              leading-none
              tracking-[-0.06em]
              text-[#020F40]/[0.14]
              dark:text-white/[0.09]
              sm:text-[11vw]
              lg:text-[9vw]
            "
          >
            {footer.watermark}
          </div>
        </div>
      </div>
    </footer>
  );
}
