// lib/site.js — SINGLE SOURCE OF TRUTH for all pages
// Just JS, brutalist, Space Grotesk. Edit here → every page updates.

export const site = {
  name: 'The Software Base',
  shortName: 'TSB',
  title: 'Software Agency for Websites & Web Apps — The Software Base',
  description: 'The Software Base is a software agency building websites, web apps, AI systems and platforms on Next.js + MongoDB — production in 4–6 weeks.',
  url: 'https://thesoftwarebase.com',
  email: 'thesoftwarebase@gmail.com',
  year: '2026',
  locale: 'en_US',
  keywords: ['software agency', 'web development agency', 'website development', 'web app development', 'app development', 'AI agency', 'AI automation', 'SaaS development', 'MVP development', 'Next.js agency', 'MongoDB', 'platform engineering', 'startup software', 'The Software Base', 'TheJobStarter'],
  authors: [{ name: 'The Software Base', url: 'https://thesoftwarebase.com' }],
  creator: 'The Software Base',
  publisher: 'The Software Base',
  nav: [
    { href: '/services', label: 'Services', desc: 'Product, platform, AI systems' },
    {
      href: '/work',
      label: 'Work',
      desc: 'Selected case studies',
      children: [
        { href: '/work/products', label: 'Products', desc: 'Own products — designed, built & shipped' },
        { href: '/work/clients', label: 'Clients', desc: 'Client delivery, same process' },
      ],
    },
    { href: '/process', label: 'Process', desc: 'How we ship at scale' },
    { href: '/why-us', label: 'Why us?', desc: 'Sharp edge, proven scale' },
  ],
  cta: { label: 'Start a project', href: '/contact' },
  ui: {
    navTitle: 'Navigation',
    systemOperational: 'System operational',
    systemOperationalLong: 'System operational',
    backToTop: 'Back to top',
    closeNavigation: 'Close navigation',
    openNavigation: 'Open navigation',
    skipToContent: 'Skip to content',
    themeLight: 'Switch to light mode',
    themeDark: 'Switch to dark mode',
    themeLightShort: 'Light mode',
    themeDarkShort: 'Dark mode',
  },
};

export const pages = {
  services: {
    kicker: 'Services',
    title: ['Software that ships,', 'then holds at scale.'],
    desc: 'Full-stack product engineering on Next.js and MongoDB — interfaces, APIs, data, deployment and AI systems, taken from first call to production in 4–6 weeks.',
    primaryCta: { label: 'Start a project', href: '/contact' },
    secondaryCta: { label: 'See work', href: '/work/products' },
    // home-specific (no hardcoding in components)
    homeTitle: ['What', 'we ship'],
    homeStats: [
      { v: '6', k: 'Core services' },
      { v: '4–6w', k: 'To production' },
      { v: '99.9%', k: 'Uptime target' },
    ],

    cardCta: 'Start a project',
    exploreCta: 'Explore all services',
    countSuffix: 'core services',
    labKicker: 'Proof, not promises',
    labTitle: ['Lab —', 'Working proof'],
    labCountSuffix: 'live proofs',
    labDesc: 'Four live experiments built with the same stack we ship for clients — preview deployments, real-time monitoring, edge distribution and a token-driven design system.',
    labs: [
      { name: 'Preview Deployments', description: 'Every project gets a live URL on day three. This marquee runs on the same CI pipeline your website ships with.', href: '/contact', cta: 'Start a project', bulletsFrom: 0, span: 'col-span-3 lg:col-span-1' },
      { name: 'Live Monitoring', description: 'Uptime, traces and alerts on every launch. This feed mirrors the observability dashboard your web app gets.', href: '/contact', cta: 'Start a project', bulletsFrom: 1, span: 'col-span-3 lg:col-span-2' },
      { name: 'Edge Performance', description: 'Pages served from the edge, worldwide. This beam visualizes the network your platform runs on.', href: '/contact', cta: 'Start a project', bulletsFrom: 2, span: 'col-span-3 lg:col-span-2' },
      { name: 'Design Tokens', description: 'One token system driving light and dark themes. This calendar is themed entirely by tokens, like your app will be.', href: '/contact', cta: 'Start a project', bulletsFrom: 3, span: 'col-span-3 lg:col-span-1' },
    ],
  },
  work: {
    kicker: 'Selected work',
    title: ['Selected', 'case studies.'],
    desc: 'Production software with real users and real metrics — designed, built and operated to hold at scale.',
    // home-specific
    homeKicker: 'Work — built & shipped',
    homeTitle: ['Software we built.', 'Systems that hold.'],
    viewAllLabel: 'View all work',
    ownBadge: 'Own • Product',
    clientsKicker: 'Client work',
    scrollHint: 'Scroll →',
    clientBadge: 'Client',
    moreWorkTitle: 'More work',
    moreWorkCta: 'View all →',
    productsTitle: ['Own', 'products.'],
    productsDesc: 'Own products in production — including TheJobStarter, a placement-prep platform serving students and coaching centers.',
    productsShort: 'TheJobStarter, live in production.',
    clientsTitle: ['Client', 'work.'],
    clientsDesc: 'Client engagements shipped with the same process — fixed scope, weekly demos, production in weeks.',
    clientsShort: 'Client delivery, same proven process.',
  },
  process: {
    kicker: 'Process',
    title: ['How we', 'ship.'],
    desc: 'A fixed four-phase engagement — discover in 48 hours, build with weekly demos, ship with observability, then scale on evidence.',
    timeline: '4–6 weeks',
    // home deck — all labels from lib
    deckMetaSuffix: 'phases • fixed timeline',
    headerExtra: 'Every engagement runs the same four phases with visible milestones — you always know what ships next and when.',
    badges: { stacked: 'Milestone-gated', overlap: 'Demo every week' },
    hintBar: { mobile: 'Scroll to walk the timeline', desktop: 'Four phases, end to end', scrollHint: 'Walk the timeline' },
    card: {
      phaseLabel: 'Phase',
      stepLabel: 'STEP',
      yieldsLabel: 'Next →',
      productionFallback: 'Production • 99.9% uptime',
      activateLabel: 'Start a project',
      dbBadge: 'Fixed scope • No surprises',
      goLabel: 'Next',
    },
    scalesKicker: 'Fixed scope • Weekly demos • 4–6 weeks',
    timelineLabel: 'Timeline',
    timelineSuffix: 'to production',
    ctaDesc: 'One team from discovery to production. Fixed scope after day two, a working preview by day three, and observability from the first deploy.',
    ctaDescSuffix: 'Start in 48 hours, previews on day 3.',
    primaryCta: 'Start in 48 hours',
    secondaryCta: 'See the phases',
    stagesSuffix: 'phases, shipped',
    toProd: 'to production',
  },
  whyUs: {
    kicker: 'Why us?',
    title: ['Sharp edge,', 'proven scale.'],
    desc: 'One senior team that designs, builds and operates your product — fixed scope, weekly demos, production in 4–6 weeks, and 99.9% uptime after launch.',
    homeTitle: ['Why teams', 'hire us'],
    homeCta: 'More reasons',
    primaryCta: { label: 'Start a project', href: '/contact' },
    secondaryCta: { label: 'See proof', href: '/work/products' },
    reasonsKicker: 'Sharp edge',
    reasonsSuffix: 'reasons',
    compareKicker: 'Them vs us',
    compareTitle: ['Them vs', 'us.'],
    themTitle: 'Typical agency',
  },
  contact: {
    kicker: 'Contact — 24h reply',
    title: ['Start a', 'project.'],
    desc: 'Tell us what you want to build. We reply within 24 hours with sharp questions and a realistic timeline.',
  },
  notFound: {
    kicker: '404 — Not found',
    title: ['LOST', 'IN CIRCUIT.'],
    desc: 'This route does not exist — let us route you back.',
    primaryCta: { label: 'Go home', href: '/' },
    secondaryCta: { label: 'Contact', href: '/contact' },
  },
  error: {
    kicker: 'System fault',
    title: ['Something', 'broke.'],
    desc: 'A client-side fault tripped the circuit breaker. Your data is safe — reset the breaker and continue.',
    retryLabel: 'Reset breaker',
  },
  privacy: {
    kicker: 'Legal — Privacy',
    title: ['Privacy', 'Policy.'],
    desc: 'How we collect, use, and protect your data — complete clarity, no legal theater.',
    updated: 'Last updated: August 2026',
    sections: [
      { title: '01 — Data we collect', body: 'We collect only what we need to ship: name, work email, project details you submit via /contact, and usage metrics via MongoDB. No tracking pixels, no soft shadows.' },
      { title: '02 — How we use it', body: 'To reply within 24h, to build your Next.js + Just.js + MongoDB system, and to monitor in production. We do not sell data. Flat fill, not gradient — data stays with us.' },
      { title: '03 — Storage & security', body: 'MongoDB with access controls, encryption at rest, and hard 3px borders around every surface — literal and figurative. Retention: project data 12 months after handoff, then purged.' },
      { title: '04 — Your rights', body: 'Access, correct, delete — email hello@thesoftwarebase.com. We reply in 6 hours avg. No Figma theater, just action.' },
      { title: '05 — Contact', body: 'Questions? hello@thesoftwarebase.com — The Software Base, Remote-first, Est. 2024.' },
    ],
  },
  terms: {
    kicker: 'Legal — Terms',
    title: ['Terms', 'of Service.'],
    desc: 'Rules for using The Software Base — hard borders, hard promises.',
    updated: 'Last updated: August 2026',
    agreeLabel: 'I agree to these terms',
    sections: [
      { title: '01 — Acceptance', body: 'Using thesoftwarebase.com and our services means you accept these terms. Hard borders, hard promises — no soft shadows.' },
      { title: '02 — Services', body: 'We deliver Next.js + Just.js + MongoDB systems, 4–6 weeks to prod, with 3px borders and 0–4px radius. Scope is frozen after Discover — no feature creep.' },
      { title: '03 — Your responsibilities', body: 'Provide access, content, and decisions within 48h. Delays shift timelines. We stay focused — no scope creep.' },
      { title: '04 — Intellectual property', body: 'You own the shipped code and content after payment. We retain the right to showcase selected work in our portfolio (with your approval).' },
      { title: '05 — Limitation', body: 'Liability capped at fees paid. No soft guarantees — we ship with monitoring, rollback plans, and systems built to hold in production.' },
      { title: '06 — Contact', body: 'Questions? hello@thesoftwarebase.com — Remote-first, Est. 2024.' },
    ],
  },
  homeCta: {
    title: 'Have something to ship?',
    desc: 'Tell us what you are building — we reply within 24 hours with next steps.',
  },
  homeFaq: {
    kicker: 'Questions, answered',
    title: 'FAQ',
    desc: 'Straight answers on process, stack, pricing and support.',
    cta: { label: 'Still stuck? Contact', href: '/contact' },
    countLabel: 'questions',
    answerLabel: 'Answer',
    stats: [
      { v: '24h', k: 'avg reply' },
      { v: '6', k: 'answers' },
    ],
  },
};

export const hero = {
  kicker: 'Precision Engineering — Since 2024',
  title: ['Software that ships,', 'then holds at scale.'],
  desc: 'We combine brutalist clarity with engineering depth. No gradients on buttons, no soft shadows — just hard borders, sharp corners, and systems that last in production.',
  primaryCta: { label: 'Start a project', href: '/contact' },
  secondaryCta: { label: 'See work', href: '/work/products' },
  video: '',
  poster: '/home-hero.webp',
  stats: [
    { v: '6w', k: 'avg to prod' },
    { v: '99.9%', k: 'uptime' },
    { v: '40%', k: 'faster p95' },
  ],
};

export const services = [
  {
    kicker: '01 — Product',
    title: 'Product Engineering',
    desc: 'Full-stack web products built with Next.js and MongoDB. Clean interfaces, scalable architecture, and fast delivery without cutting corners.',
    bullets: ['Design systems', 'API and database architecture', 'Performance and accessibility'],
    image: '/home-hero.png',
    imagePos: 'object-top',
    selected: true,
  },
  {
    kicker: '02 — Platform',
    title: 'Platform & Infrastructure',
    desc: 'From first deploy to production on Cloudflare or Vercel. Authentication, billing, and multi-tenancy set up correctly from the start.',
    bullets: ['Edge and serverless deployment', 'CI/CD with preview builds', 'Security by default'],
    image: '/home-hero.png',
    imagePos: 'object-center',
    selected: true,
  },
  {
    kicker: '03 — AI',
    title: 'AI Systems',
    desc: 'Agents, retrieval, and automated workflows built for real use. Every system ships with evaluation and monitoring, not just a demo.',
    bullets: ['Agents and workflow automation', 'Vector search and retrieval', 'Evaluation and monitoring'],
    image: '/home-hero.png',
    imagePos: 'object-bottom',
    selected: true,
  },
  {
    kicker: '04 — Design',
    title: 'Design Systems',
    desc: 'A consistent visual language built on tokens, typography, and reusable components. One system that works in both light and dark themes.',
    bullets: ['Design tokens and theming', 'Reusable component library', 'Accessibility and performance'],
    image: '/home-hero.png',
    imagePos: 'object-center',
    selected: false,
  },
  {
    kicker: '05 — Growth',
    title: 'Growth Engineering',
    desc: 'Analytics, funnels, and experiments that turn traffic into customers. Measurable improvements from first visit through retention.',
    bullets: ['Analytics and event tracking', 'A/B testing and feature flags', 'SEO and page speed'],
    image: '/home-hero.png',
    imagePos: 'object-top',
    selected: false,
  },
  {
    kicker: '06 — Support',
    title: 'Support & Operations',
    desc: 'Ongoing monitoring, on-call coverage, and improvements after launch. Your product stays stable as usage grows.',
    bullets: ['Observability and alerting', 'On-call and uptime targets', 'Scaling and cost control'],
    image: '/home-hero.png',
    imagePos: 'object-bottom',
    selected: false,
  },
];

export const workCases = [
  {
    slug: 'the-software-base',
    title: 'The Software Base',
    tag: 'Own • Platform • Next.js',
    desc: 'Our own proven platform — Next.js + Just.js + MongoDB, circuit design system, real-time dashboards.',
    longDesc: 'The Software Base is our own proven platform — built to prove we ship what we sell. Next.js App Router, Just.js, MongoDB, Tailwind, Space Grotesk, and hard 4px borders throughout. No soft shadows, no gradients on buttons — just systems that hold in production.',
    href: '/work/the-software-base',
    external: 'https://thesoftwarebase.com',
    kind: 'own',
    image: '/home-hero.png',
    stack: ['Next.js', 'Just.js', 'MongoDB', 'Tailwind'],
    highlights: ['Real-time dashboards', '99.9% uptime', '40% faster'],
    selected: true,
  },
  {
    slug: 'circuit-os',
    title: 'Circuit OS',
    tag: 'Own • AI • Agents SDK',
    desc: 'Agent workflow for ops: RAG, evals, durable execution. From demo to prod in 6 weeks.',
    longDesc: 'Circuit OS turns ops runbooks into durable agents. RAG over your docs, evals for reliability, Workflows for execution. From demo to prod in 6 weeks with observability from day one.',
    href: '/work/circuit-os',
    external: 'https://circuit-os.thesoftwarebase.com',
    kind: 'own',
    image: '/home-hero.png',
    stack: ['Agents SDK', 'Workflows', 'Vectorize', 'MongoDB'],
    highlights: ['6w to prod', 'Evals built-in', 'Durable'],
    selected: true,
  },
  {
    slug: 'atlas-platform',
    title: 'Atlas Platform',
    tag: 'Client • Fintech • Next.js • MongoDB',
    desc: 'Rebuilt core ledger and dashboard. 40% faster p95, high-contrast design system, real-time sync.',
    longDesc: 'Atlas needed a ledger that holds at scale and a dashboard that feels instant. We rebuilt core ledger, added real-time sync, and shipped a high-contrast design system that traders trust.',
    href: '/work/atlas-platform',
    external: 'https://atlas.example.com',
    kind: 'client',
    image: '/home-hero.png',
    stack: ['Next.js', 'MongoDB', 'Edge'],
    highlights: ['40% faster p95', 'Real-time', 'High-contrast UI'],
    selected: true,
  },
  {
    slug: 'base-commerce',
    title: 'Base Commerce',
    tag: 'Client • E-commerce • Edge',
    desc: 'Headless commerce on Cloudflare. ISR, payments, checkout converting at 4.2%.',
    longDesc: 'Headless commerce that converts. ISR for catalog, edge payments, checkout at 4.2% conversion — built on Cloudflare with hard borders and harder performance.',
    href: '/work/base-commerce',
    external: 'https://base-commerce.example.com',
    kind: 'client',
    image: '/home-hero.png',
    stack: ['Next.js', 'Cloudflare', 'Stripe'],
    highlights: ['4.2% checkout', 'ISR', 'Edge'],
    selected: true,
  },
  {
    slug: 'meridian-labs',
    title: 'Meridian Labs',
    tag: 'Client • SaaS • Platform',
    desc: 'Multi-tenant platform with observability, auth, billing — 0 to prod in 5 weeks.',
    longDesc: 'Multi-tenant SaaS with observability, auth, and billing — from zero to prod in 5 weeks. Fast and precise.',
    href: '/work/meridian-labs',
    external: 'https://meridian.example.com',
    kind: 'client',
    image: '/home-hero.png',
    stack: ['Next.js', 'MongoDB', 'Auth'],
    highlights: ['5w to prod', 'Multi-tenant', 'Observe'],
    selected: false,
  },
  {
    slug: 'north-ai',
    title: 'North AI',
    tag: 'Client • AI • RAG',
    desc: 'RAG system with Vectorize and evals — durable agents at scale.',
    longDesc: 'RAG that holds. Vectorize, evals, and durable agents — not a demo, a system that runs at scale.',
    href: '/work/north-ai',
    external: 'https://north-ai.example.com',
    kind: 'client',
    image: '/home-hero.png',
    stack: ['Vectorize', 'Agents', 'Evals'],
    highlights: ['RAG', 'Durable', 'Scale'],
    selected: false,
  },
];

export const processSteps = [
  { n: '01', title: 'Discover', desc: 'Map the core user journey, cut nonessential features, and define the product architecture. The sprint ends with a clear build scope and decisions your team can act on.', items: ['Map the primary user flow', 'Define the first release', 'Outline system architecture', 'Agree on milestones and decisions'], duration: '48h', image: '/home-hero.png', imagePos: 'object-top' },
  { n: '02', title: 'Build', desc: 'Next.js + Just.js + MongoDB. Weekly demos, preview deploys, real data from day 3.', items: ['Next.js + Just.js', 'MongoDB schema', 'Preview deploys', 'CI pipeline'], duration: '2–4w', image: '/home-hero.png', imagePos: 'object-center' },
  { n: '03', title: 'Ship', desc: 'Hardening, a11y, perf, observability. Launch with circuit monitoring and rollback.', items: ['Accessibility audit', 'Performance hardening', 'Observability stack', 'Circuit breakers'], duration: '1–2w', image: '/home-hero.png', imagePos: 'object-bottom' },
  { n: '04', title: 'Scale', desc: 'Improve the live product using usage data and customer feedback. Expand capacity where demand requires it, while maintaining reliability and keeping new work focused.', items: ['Monitor usage and product health', 'Prioritize improvements from evidence', 'Increase capacity as demand grows', 'Maintain and support the live product'], duration: 'Ongoing', image: '/home-hero.png', imagePos: 'object-center' },
];

export const whyUs = {
  reasons: [
    { n: '01', title: 'Revenue in 4–6 weeks', desc: 'Hard deadlines, preview deploys day 3, production in 4–6 weeks. No 6-month agency theater — you ship, charge, and iterate while competitors still wireframe.' },
    { n: '02', title: 'One team, zero handoff', desc: 'Design, Next.js + Just.js + MongoDB, infra, and billing from one Slack channel. No design-to-dev handoff, no lost context, fixed price.' },
    { n: '03', title: 'AI that pays, not demos', desc: 'RAG, Agents SDK, and Workflows with evals, observability, and durable execution. Agents that handle ops in production — not a video demo.' },
    { n: '04', title: 'You own it, we run it', desc: 'On Cloudflare/Vercel with observability, rollback, and 99.9% uptime. You own code, data, and infra — we stay 24h on-call, no vendor lock-in.' },
  ],
  stats: [
    { v: '6w', k: 'avg to prod' },
    { v: '99.9%', k: 'uptime' },
    { v: '40%', k: 'faster p95' },
    { v: '24h', k: 'avg reply' },
  ],
  compare: {
    them: ['Months of Figma, no ship date, zero revenue', '3 vendors, handoff hell, context lost', 'Demo AI, no evals, breaks in prod', 'Vendor lock-in, no observability, weak SLAs'],
    us: ['Preview day 3, prod in 4–6 weeks, revenue now', 'One team, one Slack, fixed price, no handoff', 'Evals + observability, durable in production', 'You own code + infra, 99.9% uptime, 24h on-call'],
    badge: 'Proven in production',
  },
};

export const contact = {
  kicker: 'Contact — 24h reply',
  title: ['Start a', 'project.'],
  desc: 'Tell us what you want to build. We reply within 24 hours — no sales theater.',
  budgets: ['25k — 50k', '50k — 100k', '100k+'],
  promise: 'Avg reply — 6 hours • thesoftwarebase@gmail.com',
  formKicker: 'Contact form',
  directKicker: 'Direct lines',
  budgetsKicker: 'Signal range',
  budgetLabel: 'Budget',
  submitLabel: 'Send inquiry',
  sendingLabel: 'Transmitting…',
  errorDesc: 'Transmission failed. Try again or use a direct line.',
  retryLabel: 'Retry transmission',
  newLabel: 'New transmission',
  emailLabel: 'Email us',
  phoneLabel: 'Call us',
  locationAttached: 'Location attached',
  locationMissing: 'Location unavailable — you can still send',
  locationEnable: 'Attach my location',
  locationLocating: 'Locating…',
  locationRequired: 'Location is required — attach it above to send your inquiry.',
  uplinkKicker: 'Uplink monitor',
  stepsKicker: 'What happens next',
  globeKicker: 'Live globe',
  globeLive: 'Position lock',
  globeWaiting: 'Acquiring signal…',
  formAction: '/api/contact',
  steps: [
    { n: '01', text: 'We reply within 24 hours with hard questions and a harder deadline.' },
    { n: '02', text: 'Preview deploys land on day 3 — real data, real pixels.' },
    { n: '03', text: 'Production in 4–6 weeks with observability from day one.' },
  ],
  fields: [
    { id: 'name', label: 'Name', type: 'text', placeholder: 'Ada Lovelace', autoComplete: 'name', required: true, half: true },
    { id: 'email', label: 'Work email', type: 'email', placeholder: 'ada@company.com', autoComplete: 'email', required: true, half: true },
    { id: 'phone', label: 'Phone', type: 'tel', placeholder: '+1 (555) 000-0000', autoComplete: 'tel', required: false, half: true },
    { id: 'message', label: 'What are you building?', type: 'textarea', placeholder: 'A fintech platform that needs real-time sync and serious speed...', autoComplete: 'off', required: true, rows: 5 },
  ],
  phoneError: 'Enter a valid phone number.',
  countryCodeLabel: 'Code',
  countryCodes: [
    { c: 'United States', d: '+1' },
    { c: 'Canada', d: '+1' },
    { c: 'United Kingdom', d: '+44' },
    { c: 'Ireland', d: '+353' },
    { c: 'Germany', d: '+49' },
    { c: 'France', d: '+33' },
    { c: 'Netherlands', d: '+31' },
    { c: 'Belgium', d: '+32' },
    { c: 'Spain', d: '+34' },
    { c: 'Portugal', d: '+351' },
    { c: 'Italy', d: '+39' },
    { c: 'Switzerland', d: '+41' },
    { c: 'Austria', d: '+43' },
    { c: 'Sweden', d: '+46' },
    { c: 'Norway', d: '+47' },
    { c: 'Poland', d: '+48' },
    { c: 'Turkey', d: '+90' },
    { c: 'Israel', d: '+972' },
    { c: 'Saudi Arabia', d: '+966' },
    { c: 'Qatar', d: '+974' },
    { c: 'Kuwait', d: '+965' },
    { c: 'UAE', d: '+971' },
    { c: 'Egypt', d: '+20' },
    { c: 'Nigeria', d: '+234' },
    { c: 'South Africa', d: '+27' },
    { c: 'India', d: '+91' },
    { c: 'Pakistan', d: '+92' },
    { c: 'Singapore', d: '+65' },
    { c: 'Malaysia', d: '+60' },
    { c: 'Indonesia', d: '+62' },
    { c: 'Philippines', d: '+63' },
    { c: 'Japan', d: '+81' },
    { c: 'China', d: '+86' },
    { c: 'Australia', d: '+61' },
    { c: 'New Zealand', d: '+64' },
    { c: 'Brazil', d: '+55' },
    { c: 'Mexico', d: '+52' },
  ],
  success: {
    title: ['Signal', 'received.'],
    desc: 'Your inquiry is in the queue. We reply within 24 hours — no sales theater.',
  },
};

export const faq = [
  { q: 'How fast do you ship?', a: '4–6 weeks to production. Discover in 2 days, build with weekly demos, ship with observability from day one.' },
  { q: 'What stack do you use?', a: 'Next.js + Just.js + MongoDB on Cloudflare/Vercel. Fullstack JS, no handoffs, edge-ready.' },
  { q: 'Do you do AI?', a: 'Yes — Agents SDK, Workflows, Vectorize with evals. Not demos, durable agents that run in production.' },
  { q: 'What about design?', a: 'Clean and confident: 3px borders, 0–4px radius, flat fills, hard shadows. Fast, legible, no decoration for its own sake.' },
  { q: 'What is the cost?', a: '25k–100k+ depending on scope. Fixed price, preview deploys, no surprise.' },
  { q: 'Do you support after launch?', a: 'Yes — monitoring, iterations, and scale. We stay on-call, no feature creep.' },
];

export const workVisibility = {
  clientsEnabled: false,
};

export const workDetail = {
  badges: { own: 'Own • Product', client: 'Client • Work' },
  visitLive: 'Visit live',
  internalUse: 'For internal use',
  startSimilar: 'Start similar',
  galleryKicker: 'Gallery',
  backToWork: 'Back to work',
  moreProducts: 'More products',
  moreClients: 'More clients',
  breadcrumb: { work: 'Work', products: 'Products', clients: 'Clients' },
  kindLabel: { own: 'Own product — ', client: 'Client — ' },
  ghost: { own: 'OWN', client: 'CLIENT' },
};

export const footer = {
  tagline: 'Software designed, built and operated — production in 4–6 weeks.',
  cols: [
    { title: 'Product', links: [{ label: 'Services', href: '/services' }, { label: 'Work', href: '/work/products' }, { label: 'Process', href: '/process' }, { label: 'Why us', href: '/why-us' }] },
    { title: 'Legal', links: [{ label: 'Privacy', href: '/privacy' }, { label: 'Terms', href: '/terms' }, { label: 'Contact', href: '/contact' }] },
  ],
  manifesto: {
    kicker: 'Manifesto',
    title: 'Fixed scope. Weekly demos. Production in weeks.',
    desc: 'One Team, from first call to launch — and on-call after. A working preview by day three, production in 4–6 weeks, 99.9% uptime.',
    badge: '4–6 weeks to production',
  },
  legal: '© 2026 The Software Base — All rights reserved.',
  watermark: 'THESOFTWAREBASE',
  status: 'System operational',
  statusShort: 'System operational',
  remoteNote: 'Remote-first',
  shipNote: 'Production in 4–6 weeks',
  builtNote: 'Built to last',
  craftedPrefix: 'Shipped by —',
  backToTop: 'Back to top',
};

export const auth = {
  loginKicker: 'Restricted — Admins only',
  loginTitle: ['Agency', 'console.'],
  loginDesc: 'Sign in to manage every section of the site. Short-lived sessions, hard borders, zero theater.',
  emailLabel: 'Admin email',
  passwordLabel: 'Password',
  submitLabel: 'Unlock console',
  sendingLabel: 'Verifying…',
  errorInvalid: 'Invalid email or password.',
  errorGeneric: 'Sign-in failed. Try again.',
  logoutLabel: 'Sign out',
  backLabel: 'Back to site',
};

export const dashboard = {
  activityTitle: 'Recent Activity',
  kicker: 'Mission control',
  homeTitle: ['Mission', 'control.'],
  homeDesc: 'Every section of the site, editable. Pick a module — changes go live on publish.',
  backLabel: 'Back to dashboard',
  soonLabel: 'Soon',
  editor: {
    saveLabel: 'Save changes',
    savingLabel: 'Saving…',
    savedLabel: 'Saved',
    addLabel: 'Add item',
    removeLabel: 'Remove',
    sourceDb: 'Live from database',
    sourceLib: 'Defaults from code',
    sourceWarn: 'Database unreachable — saving now would overwrite live data with defaults. Reconnect, then reload this page.',
    dirtyLabel: 'Unsaved changes',
    errorSave: 'Save failed. Try again.',
    videoLabel: 'Background video',
    posterLabel: 'Poster image',
    imageLabel: 'Image',
    uploadLabel: 'Upload new',
    uploadingLabel: 'Uploading…',
    libraryLabel: 'Library',
    useLabel: 'Use',
    deleteLabel: 'Delete',
    mediaEmpty: 'No uploads yet — add the first file above.',
    mediaConfigured: 'Media library connected',
    mediaMissing: 'Media not configured — add ImageKit keys to use uploads.',
    mediaInUse: 'In use — replace it in the listed sections first.',
    undoLabel: 'Undo last save',
    undoingLabel: 'Undoing…',
    visibilityLabel: 'Show client section on the live site',
    visibilityHint: 'Off hides Clients everywhere public — nav, home strip, listing. The dashboard editors stay open so you can add work, then flip this on.',
  },
  history: {
    title: 'Backups',
    desc: 'Every save snapshots the version it replaces — restores snapshot too, so nothing is ever truly lost.',
    restoreLabel: 'Restore',
    restoringLabel: 'Restoring…',
    restoredLabel: 'Restored',
    emptyLabel: 'No backups yet — each save creates one automatically.',
    errorLabel: 'Restore failed. Try again.',
  },
  sections: [
    { id: 'hero', label: 'Hero', desc: 'Kicker, titles, CTAs, stats', href: '/dashboard/hero', ready: true },
    { id: 'services', label: 'Services', desc: 'Cards, bullets, lab, CTAs', href: '/dashboard/services', ready: true },
    { id: 'work', label: 'Work', desc: 'Case studies, tags, stack', href: '/dashboard/work/products', ready: true },
    { id: 'process', label: 'Process', desc: 'Steps, timeline, badges', href: '/dashboard/process', ready: true },
    { id: 'why-us', label: 'Why us', desc: 'Reasons, stats, compare', href: '/dashboard/why-us', ready: true },
    { id: 'faq', label: 'FAQ', desc: 'Questions and answers', href: '/dashboard/faq', ready: true },
    { id: 'contact', label: 'Contact', desc: 'Form spec, budgets, steps', href: '/dashboard/contact', ready: true },
    { id: 'inquiries', label: 'Inbox', desc: 'Every submission, read + delete', href: '/dashboard/inquiries', ready: true },
    { id: 'footer', label: 'Footer', desc: 'Columns, manifesto, legal', href: '/dashboard/footer', ready: true },
    { id: 'home', label: 'Home copy', desc: 'CTA band, FAQ headers', href: '/dashboard/home', ready: true },
    { id: 'services-copy', label: 'Services copy', desc: 'Heroes, home block, lab', href: '/dashboard/services/copy', ready: true },
    { id: 'work-copy', label: 'Work copy', desc: 'Heroes, labels, detail words', href: '/dashboard/work/copy', ready: true },
    { id: 'process-copy', label: 'Process copy', desc: 'Hero, card + CTA labels', href: '/dashboard/process/copy', ready: true },
    { id: 'why-us-copy', label: 'Why-us copy', desc: 'Hero + home headers', href: '/dashboard/why-us/copy', ready: true },
    { id: 'contact-copy', label: 'Contact copy', desc: 'Page hero title + desc', href: '/dashboard/contact/copy', ready: true },
    { id: 'site', label: 'Site & nav', desc: 'Brand, SEO, nav, channels', href: '/dashboard/site', ready: true },
  ],
  groups: [
    { page: 'Home', href: '/', items: ['hero', 'home', 'services', 'work', 'process', 'why-us', 'faq'] },
    { page: 'Services', href: '/services', items: ['services', 'services-copy'] },
    { page: 'Work', href: '/work/products', items: ['work', 'work-copy'] },
    { page: 'Process', href: '/process', items: ['process', 'process-copy'] },
    { page: 'Why Us', href: '/why-us', items: ['why-us', 'why-us-copy'] },
    { page: 'Contact', href: '/contact', items: ['contact', 'contact-copy', 'inquiries'] },
    { page: 'Global', href: null, items: ['site', 'copy', 'footer'] },
  ],
  stats: [
    { label: 'Total Users', value: '12,849' },
    { label: 'Revenue', value: '$42.9K' },
    { label: 'Active Projects', value: '28' },
  ],
  activity: [
    { title: 'Project Alpha launched', time: '2 hours ago' },
    { title: 'User signups increased 15%', time: '4 hours ago' },
    { title: 'New client onboarding', time: '1 day ago' },
  ],
};
